
*WORKING DATA SET;
DATA WORK.HRA;
  SET LAB.HRANALYTICS;
RUN;

/*-----------------------------------PRE PROCESSING --------------------------------------*/



/*------------------MISSING VALUES FOR SALARY-----------------*/
*MEDIAN FOR SALARY;
PROC MEANS DATA=WORK.HRA NOPRINT MEDIAN;
  VAR SALARY_USD;
  OUTPUT OUT=WORK.MED_SALARY MEDIAN=MED_SALARY_USD;
RUN;


*IMPUTATION;
DATA WORK.HRA;
  IF _N_ = 1 THEN SET WORK.MED_SALARY;
  SET WORK.HRA;

  IF MISSING(SALARY_USD) THEN SALARY_USD = MED_SALARY_USD;

  DROP MED_SALARY_USD;
RUN;

*DISPALY;
PROC MEANS DATA=WORK.HRA N NMISS MIN MAX MEDIAN;
  VAR SALARY_USD;
  TITLE "SALARY_USD";
RUN;


/*------------------MISSING VALUES FOR REMOTE RATIO-----------------*/
*MEAN FOR REMOTE RATIO;
PROC MEANS DATA=WORK.HRA NOPRINT MEDIAN;
  VAR REMOTE_RATIO;
  OUTPUT OUT=WORK.MED_REMOTE MEDIAN=MED_REMOTE_RATIO;
RUN;

*IMPUTATION;
DATA WORK.HRA;
  IF _N_ = 1 THEN SET WORK.MED_REMOTE;
  SET WORK.HRA;

  IF MISSING(REMOTE_RATIO) THEN REMOTE_RATIO = MED_REMOTE_RATIO;

  DROP MED_REMOTE_RATIO;
RUN;

*DISPALY;
PROC MEANS DATA=WORK.HRA N NMISS ;
  VAR REMOTE_RATIO;
  TITLE "REMOTE_RATIO";
RUN;


/*------------------MISSING VALUES FOR YEAR OF EXPERIENCE-----------------*/
*MEDIAN FOR REMOTE RATIO;
PROC MEANS DATA=WORK.HRA NOPRINT MEDIAN;
  VAR YEARS_EXPERIENCE;
  OUTPUT OUT=WORK.MED_EXP MEDIAN=MED_YEARS_EXPERIENCE;
RUN;

*IMPUTATION;
DATA WORK.HRA;
  IF _N_ = 1 THEN SET WORK.MED_EXP;
  SET WORK.HRA;

  IF MISSING(YEARS_EXPERIENCE) THEN YEARS_EXPERIENCE = MED_YEARS_EXPERIENCE;

  DROP MED_YEARS_EXPERIENCE;
RUN;


*DISPALY;
PROC MEANS DATA=WORK.HRA N NMISS MIN MAX MEDIAN;
  VAR YEARS_EXPERIENCE;
  TITLE "YEARS_EXPERIENCE";
RUN;



/*------------------MISSING VALUES FOR BENEFITS SCORE-----------------*/
*MEDIAN;
PROC MEANS DATA=WORK.HRA NOPRINT MEDIAN;
  VAR BENEFITS_SCORE;
  OUTPUT OUT=WORK.MED_BENEFITS MEDIAN=MED_BENEFITS_SCORE;
RUN;

*IMPUTATION;
DATA WORK.HRA;
  IF _N_ = 1 THEN SET WORK.MED_BENEFITS;
  SET WORK.HRA;

  IF MISSING(BENEFITS_SCORE) THEN BENEFITS_SCORE = MED_BENEFITS_SCORE;

  DROP MED_BENEFITS_SCORE;
RUN;


*DISPLAY;
PROC MEANS DATA=WORK.HRA N NMISS MIN MAX MEDIAN;
  VAR BENEFITS_SCORE;
  TITLE "BENEFITS_SCORE";
RUN;


/*------------------MISSING VALUES FOR EDUCATION REQUIRED-----------------*/
DATA WORK.HRA;
  SET WORK.HRA;
  IF MISSING(EDUCATION_REQUIRED) THEN EDUCATION_REQUIRED = "UNKNOWN";
RUN;


PROC FREQ DATA=WORK.HRA;
  TABLES EDUCATION_REQUIRED;
RUN;



/*------------------MISSING VALUES FOR COMPANY SIZE-----------------*/
DATA WORK.HRA;
  SET WORK.HRA;
  IF MISSING(COMPANY_SIZE) THEN COMPANY_SIZE = "UNKNOWN";
RUN;

PROC FREQ DATA=WORK.HRA;
  TABLES COMPANY_SIZE;
RUN;


/*----------------------------------- FEATURE ENGINEERING  --------------------------------------*/


*SALARY LOG;

DATA WORK.HRA_FE;
  SET WORK.HRA;
  IF SALARY_USD > 0 THEN LOG_SALARY = LOG(SALARY_USD);
  ELSE LOG_SALARY = .;
RUN;


*REMOTE RATIO TRANSFORMATION;
DATA WORK.HRA_FE;
  SET WORK.HRA_FE;
  LENGTH REMOTE_CAT $12;
  IF REMOTE_RATIO = 0 THEN REMOTE_CAT = "ON-SITE";
  ELSE IF REMOTE_RATIO < 100 THEN REMOTE_CAT = "HYBRID";
  ELSE IF REMOTE_RATIO = 100 THEN REMOTE_CAT = "FULLY REMOTE";
RUN;



*EXPERIENCE CATEGORY;
DATA WORK.HRA_FE;
  SET WORK.HRA_FE;
  LENGTH EXP_CAT $12;
  IF YEARS_EXPERIENCE <= 2 THEN EXP_CAT = "ENTRY";
  ELSE IF YEARS_EXPERIENCE <= 5 THEN EXP_CAT = "MID";
  ELSE IF YEARS_EXPERIENCE <= 10 THEN EXP_CAT = "SENIOR";
  ELSE EXP_CAT = "EXPERT";
RUN;


*TOTAL COMPENSATION;
DATA WORK.HRA_FE;
  SET WORK.HRA_FE;
  TOTAL_COMP_SCORE = LOG_SALARY + BENEFITS_SCORE;
RUN;


*AVERAGE SALARY BY COMPANY SIZE;
PROC SORT DATA=WORK.HRA;
  BY COMPANY_SIZE;
RUN;

PROC SORT DATA=WORK.SIZE_SAL_MEAN_CLEAN;
  BY COMPANY_SIZE;
RUN;


DATA WORK.HRA_FE;
  MERGE WORK.HRA WORK.SIZE_SAL_MEAN_CLEAN;
  BY COMPANY_SIZE;
  COMPANY_SIZE_SALARY_PREMIUM = SALARY_USD - AVG_SIZE_SALARY;
RUN;




/*----------------------------------- EDA  --------------------------------------*/

*DISTRIBUTION OF TOTAL COMPENSATION;
PROC SGPLOT DATA=WORK.HRA_FE;
  HISTOGRAM TOTAL_COMP_SCORE;
  DENSITY TOTAL_COMP_SCORE;
  TITLE "DISTRIBUTION OF TOTAL COMPENSATION";
  FOOTNOTE "GLOBAL AI JOB MARKET ANALYSIS";
RUN;



*LOG SALARY VS EXPERIENCE CATEGORY;
PROC SGPLOT DATA=WORK.HRA_FE;
  VBOX LOG_SALARY / CATEGORY=EXP_CAT;
  TITLE "LOG SALARY BY EXPERIENCE CATEGORY";
  FOOTNOTE "GLOBAL AI JOB MARKET ANALYSIS";
  
RUN;


*LOG SALARY BY REMOTE WORK;
PROC SGPLOT DATA=WORK.HRA_FE;
  VBOX LOG_SALARY / CATEGORY=REMOTE_CAT;
  TITLE "LOG SALARY BY REMOTE WORK ";
  FOOTNOTE "GLOBAL AI JOB MARKET ANALYSIS";
RUN;


*YEARS OF EXPERIENCE AND LOG SALARY;
PROC SGPLOT DATA=WORK.HRA_FE;
  SCATTER X=YEARS_EXPERIENCE Y=LOG_SALARY;
  LOESS X=YEARS_EXPERIENCE Y=LOG_SALARY;
  TITLE "YEARS OF EXPERIENCE AND LOG SALARY";
  FOOTNOTE "GLOBAL AI JOB MARKET ANALYSIS";
RUN;


*TOTAL COMPENSATION BY EXPEERIENCE CATEGORY;
PROC SGPLOT DATA=WORK.HRA_FE;
  VBOX TOTAL_COMP_SCORE / CATEGORY=EXP_CAT;
  TITLE "TOTAL COMPENSATION BY EXPEERIENCE CATEGORY";
  FOOTNOTE "GLOBAL AI JOB MARKET ANALYSIS";
RUN;


*TOTAL COMPENSATION BY REMOTE WORK;
PROC SGPLOT DATA=WORK.HRA_FE;
  VBOX TOTAL_COMP_SCORE / CATEGORY=REMOTE_CAT;
  TITLE "TOTAL COMPENSATION BY REMOTE WORK";
  FOOTNOTE "GLOBAL AI JOB MARKET ANALYSIS";
RUN;


*SALARY IN DIFFERENT EXPERIENCE LEVELS;
PROC SGPLOT DATA=WORK.HRA_FE;
  DENSITY LOG_SALARY / GROUP=EXP_CAT;
  TITLE "SALARY IN DIFFERENT EXPERIENCE LEVELS";
  FOOTNOTE "GLOBAL AI JOB MARKET ANALYSIS";
RUN;

*TOTAL COMPENSATION BY COMPANY SIZE;
PROC SGPLOT DATA=WORK.HRA_FE;
  VBOX TOTAL_COMP_SCORE / CATEGORY=COMPANY_SIZE;
  TITLE "TOTAL COMPENSATION BY COMPANY SIZE";
  FOOTNOTE "GLOBAL AI JOB MARKET ANALYSIS";
RUN;


*CORRELATION;
PROC CORR DATA=WORK.HRA_FE;
  VAR LOG_SALARY YEARS_EXPERIENCE TOTAL_COMP_SCORE BENEFITS_SCORE;
  TITLE "CORRELATION";
  FOOTNOTE "GLOBAL AI JOB MARKET ANALYSIS";
RUN;








